--- 
 - name: install mysql-server
   action: apt name=mysql-server state=latest
 - name: Install Apache module for MySQL authentication
   apt: name=libapache2-mod-auth-mysql state=latest
 - name: Install MySQL module for PHP
   apt: name=php5-mysql state=latest
   notify:
   - restart mysql


# - name: Mysql | Set root password
#   shell: debconf-set-selections <<< 'mysql-server mysql-server/root_password password put_your_root_password'
# 
# - name: Mysql | Set root repassword
#   shell: debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password put_your_root_password'
