---
 - name: control remote ansible server
   shell: "cd /etc/ansible && ansible-playbook -i hosts playbooks/updateCode.yml >> /etc/ansible/playbooks/log/up.log"
# - name: 传状态文件回到控制端
#   shell: scp -i /root/.ssh/id_rsa   root@192.168.158.128:/etc/ansible/log/up.log  /etc/ansible/log/
# - name: 本地执行
#   shell: "cd /etc/ansible && ansible-playbook -i hosts1  qu.yml"
# - name: sendmail
#   shell: "cat /etc/ansible/log/up.log | mail -s '更新代码' shenzhonglin@ltbl.cn"
# - name: delete logfile
#   shell: echo "" > /etc/ansible/log/up.log
# - name: delete cpfile
#   shell: rm -rf /root/.ansible/cp/*
